'''
Do NOT edit this file
'''
from Xconfig import hyperparameters

cases = {
    'B1': {
             'dim':768,
             'depth':12,
             'heads': 12,
             'mlp_dim':3072,
             'batch_size': 2048,
             'lr': 3e-4,
             'epoch': 3
        },
    'B2': {
             'dim':768,
             'depth':12,
             'heads': 12,
             'mlp_dim':3072,
             'batch_size': 4096,
             'lr': 1e-4,
             'epoch': 3
        },
    'BX': {
             'dim':1024,
             'depth':16,
             'heads': 16,
             'mlp_dim':4096,
             'batch_size': hyperparameters['batch_size'],
             'lr': hyperparameters['lr'],
             'epoch': hyperparameters['epoch']
        }
}
